export enum EMainContextConsts {
	// SET_SCREEN_SIZE = 'SET_SCREEN_SIZE',
	SET_CURRENT_COLOR_MODE = 'SET_CURRENT_COLOR_MODE',
	SET_CURRENT_THEME_MODE = 'SET_CURRENT_THEME_MODE',
	SET_THEME_SETTINGS = 'SET_THEME_SETTINGS',
	SET_MAIN_NAV_HEIGHT = 'SET_MAIN_NAV_HEIGHT',
}
