import CustomerLayout from '@components/layouts/Customer';
import { trpc } from '@libs/trpc';
import { IHomeProps } from '@pages/index';
import { useSession, signOut, signIn } from 'next-auth/react';
import Head from 'next/head';
import React from 'react';

const HomePage = ({ starredProductsInCollection1 }: IHomeProps) => {
	const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);
	const { data: session, status } = useSession();

	console.log('starredProductsInCollection1', starredProductsInCollection1);

	return (
		<CustomerLayout>
			<Head>
				<title>Shoppy</title>
				<meta name='description' content='Generated by create-t3-app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				{status === 'loading' && <h1>Loading...</h1>}

				{session ? (
					<>
						Signed in as {session.user?.name} <br />
						{JSON.stringify(session, null, 2)} <br />
						<button type='button' onClick={() => signOut()}>
							Sign out
						</button>
					</>
				) : (
					<>
						Not signed in <br />
						<button type='button' onClick={() => signIn()}>
							Sign in
						</button>
					</>
				)}
			</div>
		</CustomerLayout>
	);
};

export default HomePage;
